---
- name: Remove any possible existing certs
  file:
    path: /greengrass/certs
    state: absent

- name: Create the directory
  file:
    path: /greengrass/certs
    state: directory

- name: Get root-CA file
  get_url:
    url: https://www.amazontrust.com/repository/AmazonRootCA1.pem
    dest: /greengrass/certs/root.ca.pem

- name: Copy Certificate
  copy:
    src: certificates/{{ certificate_id }}-certificate.pem.crt
    dest: /greengrass/certs/{{ certificate_id }}-certificate.pem.crt
    group: root
    owner: root

- name: Copy private key
  copy:
    src: certificates/{{ certificate_id }}-private.pem.key
    dest: /greengrass/certs/{{ certificate_id }}-private.pem.key
    group: root
    owner: root

- name: Restart greengrass
  service:
    name: greengrass
    state: restarted
